---
apiVersion: v1
kind: ServiceAccount
metadata:
  # labels:
  #   app.kubernetes.io/name: jenkins
  name: jenkins
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  # labels:
  #   app.kubernetes.io/name: jenkins
  name: jenkins
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  - apps
  - extensions
  resources:
  - deployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  # labels:
  #   app.kubernetes.io/name: jenkins
  name: jenkins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jenkins
subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: devops-tools

